name: ISO build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: arch-latest

    steps:
      # Check out the repository
      - uses: actions/checkout@v4

      # Install archiso
      - run: sudo pacman -S --noconfirm archiso

      # Clone the custom ISO builder repository
      - run: git clone https://github.com/Githubguy132010/BlendOS-custom-ISO-builder.git

      # Change directory to the cloned repo and build the ISO
      - run: |
          cd BlendOS-custom-ISO-builder
          sudo mkarchiso -v -w workdir/ -o out/ .

      # Move the ISO files to uploads directory
      - run: mv BlendOS-custom-ISO-builder/out/*.iso uploads/

      # Upload the built ISO as an artifact
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.2.1-node20
        with:
          name: blendos-iso
          path: uploads/*.iso
          retention-days: 7
          include-hidden-files: false
