name: ISO build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest   # Use the official Arch Linux container
      options: --privileged     # Run the container in privileged mode

    steps:
      # Install archiso and other required packages
      - name: Install Dependencies
        run: |
          pacman -Sy --noconfirm archiso grub git

      # Clone the custom ISO builder repository
      - name: Clone ISO Builder Repo
        run: git clone https://github.com/Githubguy132010/BlendOS-custom-ISO-builder.git

      # Change directory to the cloned repo and build the ISO
      - name: Build ISO
        run: |
          cd BlendOS-custom-ISO-builder
          mkarchiso -v -w workdir/ -o out/ .

      # Move the ISO files to uploads directory
      - name: Move ISO to Uploads
        run: mv BlendOS-custom-ISO-builder/out/*.iso uploads/

      # Upload the built ISO as an artifact
      - name: Upload ISO Artifact
        uses: actions/upload-artifact@v3.2.1
        with:
          name: blendos-iso
          path: uploads/*.iso
          retention-days: 7
          include-hidden-files: false
