name: Validate-YAML

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-yaml:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - name: Get Distrobox
        run: sudo apt update && sudo apt install distrobox -y

      - uses: actions/checkout@v2
      - name: Create Arch Distrobox
        run: distrobox create --name arch --image docker.io/archlinux:latest --yes && distrobox enter arch
    
      - uses: actions/checkout@v2
      - name: Get YAML file
        run: wget https://github.com/Githubguy132010/My-system/blob/main/gnome.yaml

      - uses: actions/checkout@v2
      - name: Get Akshara
        run: wget https://git.blendos.co/blendOS/system-tools/akshara/-/raw/main/akshara?ref_type=heads&inline=false akshara && wget https://git.blendos.co/blendOS/system-tools/akshara/-/raw/main/akshara-system-update.service?ref_type=heads&inline=false akshara-system-update.service  && wget https://git.blendos.co/blendOS/system-tools/akshara/-/raw/main/akshara.hook?ref_type=heads&inline=false akshara.hook &&  wget https://git.blendos.co/blendOS/system-tools/akshara/-/raw/main/akshara.install?ref_type=heads&inline=false akshara.install && wget https://git.blendos.co/blendOS/system-tools/akshara/-/raw/main/akshara.service?ref_type=heads&inline=false akshara.service
        


      - uses: actions/checkout@v2
      - name: Prepare YAML file
        run: sudo mv gnome.yaml /system.yaml

        
      - uses: actions/checkout@v2
      - name: Run Akshara update
        run: ./akshara update
